# Generated by Django 3.2.18 on 2023-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0002_auto_20230523_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='mass_status',
            field=models.CharField(default='WAITING', max_length=10),
        ),
    ]
