# Generated by Django 3.2.18 on 2023-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0003_user_job_mass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='aeTSA_annotation_status',
            field=models.CharField(default='WAITING', max_length=10),
        ),
        migrations.AddField(
            model_name='user_job',
            name='aeTSA_status',
            field=models.CharField(default='WAITING', max_length=10),
        ),
    ]
