# Generated by Django 3.2.18 on 2023-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0004_auto_20230530_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='data_preparation_status',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
