# Generated by Django 3.2.18 on 2023-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0005_user_job_data_preparation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_job',
            name='data_preparation_status',
            field=models.CharField(default='WAITING', max_length=50),
        ),
    ]
