# Generated by Django 3.2.18 on 2023-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0007_user_job_shared_neoantigen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='hla',
            field=models.CharField(default='hla', max_length=254),
        ),
    ]
