# Generated by Django 3.2.18 on 2023-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWeb', '0010_alter_user_job_hla'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='sample_names',
            field=models.CharField(default='sample_names', max_length=254),
        ),
    ]
